language: c

before_install:
  # Install dependencies
  - sudo apt-get update
  - sudo apt-get install -y automake build-essential zlib1g-dev
 
compiler:
  - gcc

script:
  - cmake . 
addons:
  apt:
    packages:
      - cmake-data
      - cmake
